version: '2'
services:
  webserver:
    build:
      context: ./build/nginx/
      args:
        - 'DEV_GID=${DEV_GID}'
        - 'DEV_UID=${DEV_UID}'
    container_name: nginx
    working_dir: /approot
    volumes:
      - '../workspace:/approot/:rw'
      - ./config/nginx/conf.d:/etc/nginx/conf.d/:ro
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx/:/var/log/nginx/:rw
    ports:
      - '80:80'
    links:
      - php-fpm
    networks:
      - dev-network
  php-fpm:
    build: 
      context: ./build/php71/
      args:
        - 'DEV_GID=${DEV_GID}'
        - 'DEV_UID=${DEV_UID}'
    container_name: php-fpm71
    working_dir: /approot
    volumes:
      - '../workspace:/approot/:rw'
      - ./config/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./config/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/php-fpm/:/var/log/php-fpm/:rw
    links:
      - mysqlserver
    ports:
      - '9000:9000'
    networks:
      - dev-network
  mysqlserver:
    image: 'mysql:5.7'
    container_name: mysql57
    working_dir: /approot
    volumes:
      - '../workspace:/approot'
      - '../db_data/mysql:/var/lib/mysql'
      - './config/mysql:/etc/mysql/conf.d'
    environment:
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
      - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
      - 'MYSQL_USER=${MYSQL_USER}'
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}' 
    restart: always
    env_file: .env
    ports:
      - '3306:3306'
networks:
  dev-network:
    driver: bridge
